### ISSUE TITLE
Requesting repository for processing ML Reproducibility Challenge 2020 Accepted papers

### ISSUE THREAD

**Issue by koustuvsinha** [ReScience/ReScience#100]
As in [our last iteration](https://github.com/ReScience/NeurIPS-2019), this year we would also be glad to have a repository under ReScience org where we can conduct editorial duties on the accepted papers. Requesting a repository for the same! Thanks!

**Comment by rougier** [comment]
Done: https://github.com/ReScience/NeurIPS-2020 (you're admin)

**Comment by koustuvsinha** [comment]
Thanks so much! :)
