### ISSUE TITLE
Discussing the Volume/Issue of MLRC 2021  

### ISSUE THREAD

**Issue by koustuvsinha** [ReScience/ReScience#107]
Hi @rougier ! Moving the discussion from #48 here.

> 49 articles! Do you think it's worth to split them in two (or more) issues if you have some criterion for splitting?

I don't have the best splitting criterion in mind, but here are some options:

- Split based on conferences - It might result in more issues (we support 9 conferences), but each issue will have less number of papers. Here is the distribution:

| Papers Accepted | Conference |
| --- | --- |
| 11 | ICML 2021 |
| 4 | ICLR 2021 |
| 4 | AAAI 2021 |
| 6 | CVPR 2021 |
| 4 | IJCAI 2021 |
| 6 | ICCV 2021 |
| 2 | NeurIPS 2021 |
| 2 | ACL 2021 |

- Split based on awards - 1 paper is awarded best paper, 5 papers are awarded outstanding paper. So we could have two issues separating 6 (+1 editorial) and 42 articles?

Let me know which way you think could be best for readability.

**Comment by rougier** [comment]
We can perfectly have a single issue with all the papers, it's only a matter of deciding what would be the most useful for the reader. Unfortunatley and given the information, I do not have a better idea than a single issue. Also, if you write the editorial, it might be easier for your to have a single issue. So let's go for a "mega issue".

**Comment by koustuvsinha** [comment]
Awesome, cool I'll go for a mega issue then! :)
