### ISSUE TITLE
Correction to Picoche et al. (2022)

### ISSUE THREAD

**Issue by CoraliePicoche** [ReScience/ReScience#109]
Dear editors,

My co-authors (@fbarraquand and W.R. Young) and I have noticed two small mistakes in the formulas of the article [[Re] Reproductive pair correlations and the clustering of organisms](https://zenodo.org/record/6546488#.YzKomtXP1H4). The results we show correspond to the right formulas and remain unchanged. Re-reading the whole paper, we also realized that we could further clarify some parts of the derivation shown in the Appendices, which we think could greatly improve the understanding of the methods by the reader.

We describe all changes we would like to make in the enclosed .pdf. We differentiate between modifications that need to be made for the article to be mathematically correct, and the explanations we would like to add to improve it.

Could we slightly modify the text and publish a second version of the article corresponding to the same doi in Zenodo?

Thank you for you help,
On behalf of all co-authors.
Coralie Picoche

[corrections_to_Picoche2022ReScience.pdf](https://github.com/ReScience/ReScience/files/9676961/corrections_to_Picoche2022ReScience.pdf)

**Comment by CoraliePicoche** [comment]
Dear editors,

We are wondering about the policy of ReScience regarding small changes in the text of an article, and the corresponding submission of a second version of an article on Zenodo. Would it be possible to make the small edits we suggest in the .pdf above?

Thank you very much,
Coralie Picoche

**Comment by pdebuyl** [comment]
Hi @CoraliePicoche sorry for the delay.

@ReScience/editors do we have a procedure for corrections?

I had a look at the attached pdf and those changes can be accepted straightforwardly as a correction.

**Comment by khinsen** [comment]
@pdebuyl Yes, we have had error corrections in the past. The updating procedure is described at https://github.com/ReScience/articles/#updating-an-already-published-article.

**Comment by CoraliePicoche** [comment]
So, if I understand correctly, we just have to send an updated version of the .pdf to the editor who first handled the submission (which would be you, @pdebuyl)?

**Comment by khinsen** [comment]
@CoraliePicoche Yes, that's all you need to do.

**Comment by pdebuyl** [comment]
In practice, the easiest is to modify the tex file in your original article repository: https://github.com/CoraliePicoche/brownian_bug_fluid

Then, I can generate the pdf and follow the metadata update procedure on zenodo.

**Comment by CoraliePicoche** [comment]
We have just pushed the edited .tex files to the repository. You will notice one additional modification: we explain slightly differently how we get the advection term in the section "Advection process" in the Supplementary. The reasoning is very similar, but our new version puts more emphasis on the equivalence between our model and the references equations of Kraichnan et al. (1974) which we use to justify our results.

**Comment by pdebuyl** [comment]
Thanks @CoraliePicoche I'll take care of this. I "just need" to re-become familiar with our publication scripts :-)

**Comment by CoraliePicoche** [comment]
Great, thank you very much @pdebuyl !

**Comment by pdebuyl** [comment]
Done,

Paper at https://zenodo.org/record/7244522

Update of ReScience record at https://github.com/ReScience/articles/pull/27
