### ISSUE TITLE
Please state copyright/license for ReScience materials

### ISSUE THREAD

**Issue by yarikoptic** [ReScience/ReScience#12]
stuff on wiki, template paper repo etc.  In the paper "Licence CC-BY-SA" should get complimented with version and probably an explicit statement of who owns the copyright (authors)

**Comment by rougier** [comment]
@khinsen 

Yes, you're right, we just forgot this part. And more problematic, we forgot the license in the first paper code repository...

Some proposal:

 * wiki site: [CC-BY-SA 4.0 international](https://creativecommons.org/licenses/by-sa/4.0/)
 * submission repo: [CC-BY-SA 4.0 international](https://creativecommons.org/licenses/by-sa/4.0/)
 * submission article repo: [CC-BY-SA 4.0 international](https://creativecommons.org/licenses/by-sa/4.0/)
 * submission code repo: [Modified BSD](https://www.debian.org/misc/bsd.license)
 * submission data repo: Not sure about this one
 * notebook: [Modified BSD](https://www.debian.org/misc/bsd.license)
 * material: [CC-BY-SA 4.0 international](https://creativecommons.org/licenses/by-sa/4.0/)

For the material repo, we still need to identify the original author of the enso logo because the license is not clear. Some site say it is public domain, some others don't. Last solution is to remake the logo (enso). Any help appreciated.

**Comment by yarikoptic** [comment]
>   • submission data repo: Not sure about this one

PDDL (http://opendatacommons.org/licenses/pddl/1.0/) or CC Zero?

**Comment by rougier** [comment]
Thanks, and another reference to a very good paper on licenses: http://www.gigasciencejournal.com/content/4/1/31

**Comment by yarikoptic** [comment]
On Fri, 04 Sep 2015, Nicolas P. Rougier wrote:

> Thanks, and another reference to a very good paper on licenses: [1]http://
> www.gigasciencejournal.com/content/4/1/31

;) thanks

**Comment by rougier** [comment]
Your paper is really useful (I'll put it in the references).
Can you make a PR for the ReScience-submission repo ?

**Comment by eddelbuettel** [comment]
Could I suggest a boolean OR for the code licenses to allow other Open Source licenses besides BSD?

**Comment by rougier** [comment]
I don't see much problem with that but I'm not too much specialized in license issues. What kind of license do you have in mind ?

**Comment by rougier** [comment]
@yarikoptic Do you know if there is a condensed CC BY SA 4.0 that can be included in the different repo or do we have to put the full license text ?

**Comment by jfergie03** [comment]
I'd knock it the duck off if I was you!

**Comment by eddelbuettel** [comment]
@rougier How about we say something like 

> Code under a standard Open Source license such as Apache, BSD, GPL, or compatable

The key would then be to define the set.  I know R and CRAN so much better than Python and Pypi -- R's package checker validates against [this file listing known FOSS licenses](https://github.com/wch/r-source/blob/trunk/share/licenses/license.db).

**Comment by pdebuyl** [comment]
Debian has [The Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines). They have a list of licenses that are conforming to these guidelines in their archives: https://www.debian.org/legal/licenses/ . They also list licenses that go in their "non-free" and "contrib" archives on the same page.

**Comment by rougier** [comment]
So we need to:
* [ ] Add a paragraph in the WRITE section telling authors to choose one license for their code among those listed by Debian
* [ ] Add a paragraph in the EDIT section telling editors to ensure one license has been added within the code repo
* [ ] Add a FAQ entry explaining licenses
* [ ] Add proper CC-BY-SA 4.0 in the submission template repository

**Comment by pdebuyl** [comment]
Why is there a change from CC-BY to CC-BY-SA?

**Comment by rougier** [comment]
Where ? I thought the CC-BY-SA is  pretty standard (share alike and attribution)

**Comment by eddelbuettel** [comment]
Thanks for linking to Debian. That is indeed a very good resource (as I say with my Debian maintainer hat on) but I didn't want to came across as too preachy.  GitHub also maintains a [good page](https://help.github.com/articles/open-source-licensing/) as well as a [chooser tool](http://choosealicense.com/).

**Comment by rougier** [comment]
I trust Debian on license issue.
@khinsen @pdebuyl what do you think ?

**Comment by rougier** [comment]
But the chooser tool is pretty cool. Maybe it's worth adding the link (and keep Debian link)

**Comment by pdebuyl** [comment]
The chooser appears for new repositories only, not upon forking. Although it is intended to be neutral, github's page on license has preferences (namely, MIT, Apache and GPL) and I find it a bit confounding in that it mixes a pedagogical aspect with a shortcut to pick one of the mentioned licenses.

I also support Debian's view on licenses and the site that we reference has less bias in that it does not claim to make the choice for you. They give a short list as example (not guidance though) that include GPL and BSD for code.

**Comment by eddelbuettel** [comment]
I am fully on board with what @pdebuyl stated.  The can get overbearing and moralistic.  I have a strong personal preference for GPL; others like BSD better.  Either is fine for our purposes here (and this is not the place for yet another discussion on this).

**Comment by rougier** [comment]
Ok then. Default is BSD and people are free to choose the one they like. We keep the FAQ as it is.

Last question concerning CC-BY vs CC-BY-SA, are we ok with CC-BY-SA for text (article and website) ?

**Comment by eddelbuettel** [comment]
I strongly urge you not to impose a default.  

How about:  
> Submitters may choose from a set of well-understood licenses including BSD, GPL or Apache. 

Recommendations are normative. That is not our role.  We want to validate good science and good practice.  That does rely on a single license.

**Comment by rougier** [comment]
Ok, I'll remove the default LICENSE.txt in the code repository.

**Comment by eddelbuettel** [comment]
:+1:

**Comment by rougier** [comment]
See https://github.com/ReScience/ReScience-submission/blob/master/code/README.md

**Comment by pdebuyl** [comment]
fine with me :+1: for no default.

plos uses CC-BY https://www.plos.org/open-access/ , this is also the case for the New Journal of Physics (APC-based open access since some time), Physical Review X (also uses APC, online only), the proceedings of SciPy and EuroSciPy.

I would be inclined to choose that :-)

**Comment by rougier** [comment]
Interesting, I chose the license according to PLOS license but I must have made an error.
Ok then for CC-BY (article and this website). @pdebuyl Can you make a PR ?

**Comment by khinsen** [comment]
It seems I am a bit late to the party, but still...

1. The reference to Debian for explaining licenses is fine with me. Whatever people may believe about the qualities of Debian as a Linux distribution, its rigorous treatment of licenses is generally recognized.

2. I am absolutely not a license expert, but I keep hearing that there are good reasons for distinguishing between code (GPL, BSD, ...) and prose (CC in all its variants). Has any license expert discussed the consequences for mixed works, combining code and prose? That's exactly what our papers are.

**Comment by pdebuyl** [comment]
Interesting question on mixed works. The ReScience submission repository has no "main" license file, the license is explicitly given for each of article, code, data and notebook. To me, it makes the situation clear enough.

**Comment by ctb** [comment]
I would suggest making it clearer that it has to be an OSI-approved license for code...

**Comment by eddelbuettel** [comment]
:+1: re OSI

(Also, @khinsen to keep the temperature down here, why don't we leave things best discussed over a hot or cold beverage out of these threads?  Or else we may degenerate into vi-vs-emacs in no time...)

**Comment by dhimmel** [comment]
> Ok then for CC-BY (article and this website)

+1, share alike stipulations create lots of [incompatibilities](https://wiki.creativecommons.org/wiki/Wiki/cc_license_compatibility). I think SA is a major barrier to reuse -- at least for my project, it's [causing](http://thinklab.com/discussion/integrating-resources-with-disparate-licensing-into-an-open-network/107) several headaches. CC-BY is the standard for open access articles.

> Has any license expert discussed the consequences for mixed works, combining code and prose?

The CC0 (public domain) license works for code, data, and prose. I believe the other CC licenses are not well-suited for code, although version 4.0 resolved some of the issues. In general, data licensed under anything other than CC0 is problematic.

**Comment by rougier** [comment]
I'm closing this issue now. Current status is:

*  `code`: authors are free to use any open license they prefer
*  `article`: CBY 4.0
*  `data`: CC 0
* `repository`:  authors are free to use any open license they prefer
