### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by katyhuff** [ReScience/ReScience#13]
There's a typo, but unfortunately, I can't make a PR to fix it because it's in the wiki. :( 

Anyway, in the submission page, you have:

```
Issue a pull request (PR) to ReScience with title "Review Request" and insert the followin text in the description:
```

followin needs a "g" at the end.

**Comment by rougier** [comment]
Thanks. We're working on a (temporary) solution to allow PR on the wiki. See #9

**Comment by rougier** [comment]
I've setup the wiki repo at: https://github.com/ReScience/ReScience-wiki

**Comment by katyhuff** [comment]
gotcha. Though of course I have no authority here, I'd say @khinsen is right that a jekyll github site is more editable and potentially beautiful than the wiki solution in the longer term.

**Comment by rougier** [comment]
Totally agree. @ido posted in #9 what could be the solution (modulo website design).

**Comment by ctb** [comment]
On Fri, Sep 04, 2015 at 10:29:09AM -0700, Nicolas P. Rougier wrote:
> Totally agree. @ido posted in #9 what could be the solution (modulo website design).

(pretty sure github pages does most of that without the added complexity
of Travis etc. etc.  ReadThedocs also.)

**Comment by ido** [comment]
@ctb GitHub Pages don't get indexed by Google, Yahoo, etc. properly, and having a CI script and a droplet lets you do other things too, like run any apps you need, see previews, run tests, prevent changes to certain folders, etc. that you can't do with GH Pages.  (There are other reasons, but I'm working on other things right now, if you read the link you'll see a few other reasons.)  Also, regardless of which direction you take, rescience should exist on its own domain (CNAME feature in GH pages; DigitalOcean/AWS free tier/whatever + DNS)

**Comment by ctb** [comment]
On Fri, Sep 04, 2015 at 11:21:12AM -0700, Ido Rosen wrote:
> @ctb GitHub Pages don't get indexed by Google, Yahoo, etc. properly, and having a CI script and a droplet lets you do other things too, like run any apps you need, see previews, run tests, prevent changes to certain folders, etc. that you can't do with GH Pages.  (There are other reasons, but I'm working on other things right now, if you read the link you'll see a few other reasons.)  Also, regardless of which direction you take, rescience should exist on its own domain (CNAME feature in GH pages; DigitalOcean/AWS free tier/whatever + DNS)

OK - for an unfunded and new effort this is taking on a pretty sizable
maintenance burden, though!

**Comment by rougier** [comment]
Yes, maybe we can start simple (pelican / github pages) and see how things go.
Most urgent is to correct my terrible English...

**Comment by rougier** [comment]
Let's move this discussion to #9
