### ISSUE TITLE
scientific area outside the editorial board expertise

### ISSUE THREAD

**Issue by kotzino** [ReScience/ReScience#15]
Hi all,
congrats for a very interesting effort.
My question is: whom to contact if I would like to be part of the effort but my area is outside of the existing expertise of the Editorial Board?
I am working in Databases (and Data Management in general) and with the explosion of data we have a lot of interesting cases that would fall under the journal's interests of re-science.
Please let me know,

Best regards,

Dimitris

-- 
Dimitris Kotzinos
Professor
Head MIDI team
Lab. ETIS (ENSEA/UCP/CNRS UMR 8051)
& Dept. Sciences Informatiques, Université de Cergy-Pontoise
2 av. Adolphe Chauvin
Site Saint Martin, bureau A561
95000 Pontoise
France
phone: +33 13425 2855
e-mail: Dimitrios.Kotzinos@u-cergy.fr

**Comment by rougier** [comment]
I'm not sure yet actually. Do you have some references for the paper you've in mind ?

**Comment by kotzino** [comment]
Hi again,
I do not have at the moment a specific paper in mind. I was just wondering how to join the effort and if you think some expansion towards data science would be useful for the journal to attract more submissions.

Thanks for replying,
Dimitris

**Comment by rougier** [comment]
We'll happily consider any data science work (as long as it is a replication) and hopefully, we'll soon have an editor.
