### ISSUE TITLE
Submit the replication of my own research not allowed

### ISSUE THREAD

**Issue by fabiansinz** [ReScience/ReScience#19]
I'd like to strongly suggest to rethink that restriction. I really like the idea of this journal, but I fear that this restriction will be a substantial limiting factor for the number of submissions and the usefulness of the journal.

A very obvious reason for this is that time is limited for all of us. Therefore, we usually never reproduce the results of an entire paper, but only the parts that are relevant to us. Would you then accept code that reproduces parts of that paper?

More importantly, I don't think that this restriction really promotes reproducible research. By only allowing reproduced results from people other than the authors, you are basically checking whether the methods part of a paper is sufficient to reproduce the results. While that should be the case, it is unfortunately only true in rare situations. There are various reasons for this:

- Journals have word limitations.
- Condensing a complex analysis into a few paragraphs in a methods part is a daunting task and it is very easy to fail.
- The data has not been published.

The best reproduction of an analysis is its code. This is why code should always be published with a paper. Unfortunately, this is not common practice and even if the code is published, I haven't seen a single instance in which it was reviewed. I thought that ReScience could fill this gap perfectly and who would be better suited to supply it than then authors?

Let's say you allowed authors to publish their analysis. This would mean that they would have to provide the data (because you need to be able to run it) and you would have at least one running instance that reproduces the results. It might have mistakes and biases, but at least it is one entire running instance. Others who are insterested in reproducing the paper could look at the code and, with the methods part of the paper, figure out what the authors did. If they find a error or a particular bias in the analysis, they could still submit an issue to the code repository. The time required to understand and reproduce the results, however, would be drastically reduced. I feel this would serve reproducibility much more than the hope that people spend significant time to reproduce an entire paper.

**Comment by antoine-lizee** [comment]
+1 to this, actually related to #18. Seems like using [Re:] as [Part:] could be really useful indeed.

**Comment by fabiansinz** [comment]
I am not entirely sure about the labels [Re:] and [Part:]. I guess they mean *Reproduction* and *Part*. In that case one could introduce a new one, e.g. [Org:] to say that this is the original algorithm used in the paper.

**Comment by antoine-lizee** [comment]
The labels other than [Re:] are just meant to introduce different concept than the strict Reproduction of a paper. I just made them up - we might not want to change the suffix anyway.
I meant [Part:] as "this algo is part/method of the paper".

**Comment by rougier** [comment]
It seems we'll have many submissions with partial reproduction so this is something we'll have to consider in the short term.

As for your second question, whether one can replicate its own research, the answer is no. There are several reasons (as stated in the FAQ):

1. If you made some implementation errors in the first implementation, chances are you'll made the same errors in subsequent implementations. However, if someone else tries to do replicate, he'll probably spot your error (and probably introduces its own, but original results are here to control that).

2. Trying to replicate a model from another group might be a very good way to get familiar with the work of the group and might be the opportunity for further collaborations just because you're now familiar with their research.

More importantly, what you say about checking whether one paper methods are sufficient, is one of the goal for ReScience. If the original paper methods part is not sufficient to reproduce the results, the new replication article will provide the complementary explanations. Thus, original article + replicated article will allow future replication (because the replicated code might not work ten years from now).

Are people ready to replicate a whole paper ? I think so because I did it myself (with my student) in order to have a better understanding of a specific model. We have since then improved the model and we're now publishing with the original author. Furthermore, I think replication of other's work is a good exercise for PhD students. I know a lot of them already doing that, we're now offering them an opportunity to publish it.

And of course, this does not prevent you to improve your own implementation in the meantime.

**Comment by ThomasA** [comment]
I would very much like to second @rougier on this one. The way I read @fabiansinz' proposal, this is effectively a way of publishing the code behind a paper where the code was not already published along with the paper. Excuse me, but this is just cutting the salami in thinner slices; make one publication - get one free! If you can publish your analysis and code for your own paper here then it should have already been published along with the original paper in the first place.

**Comment by antoine-lizee** [comment]
Agreed with @rougier and @ThomasA for the problem that self-replication poses. I don't think Re should become the sink for co-publication of methods along papers - this is what supplementary materials are for.

**Comment by fabiansinz** [comment]
Ok, first of all +1 for creating this journal at all. I think it was timely and needed. My suggestions were meant to improve the journal's guidelines to reach is intended goal: reproducible research. While the concern raised by @ThomasA  might be a side-effect, it was certainly was not my intention to cut the salami in thinner slices (I, for instance, publish the code for my papers on my website and/or github). I also agree that the code for a new paper should be published along with the paper. 

**However**: Let's face it, most journals (at least in my field) do not publish the code/data along with the papers. Even if they provide the possibility to upload some supplementary code, I don't know a single instance in which the reviewers have even looked at it. Since it is not enforced by journals, there is very little incentive for authors to publish the code. It would be good scientific conduct, but many people don't like the idea to publish their (often messy) code for others to see. Sometimes code to reproduce a figure does not even exist because somebody just typed in fragements into a Matlab prompt. In my field (neuroscience) it is even worse, because there is the additional general reluctance to publish the data. 

One way to increase the openly accessible code for reproducing research in papers is to give researchers an incentive to publish it. @ThomasA might call it "make one publication - get one free", but it is actually no so uncommon to publish technical details of a method used in one paper in an accompanying one. In that case, one could also argue that the technical details should have been in the methods of the original paper. 

What would be the benefits of publishing the code?

- it is reviewed
- reviews create the need for authors to clean it up
- the authors document details of the code through the accompanying paper

I don't know of a publication with accompanying code that would meet all of these three criteria. Allowing authors to publish their code in ReScience would therefore create an incentive to contribute to the availability and the quality of the code for reproducing research. 

Concerning @rougier 's comment 1: I basically agree, but I want to mention that the situation is symmetric with respect to the methods. Explanations of how an analysis was performed can be unclear because of implicit assumptions the authors made (that one is *very* common), copy-paste errors, or simple spelling mistakes (esp. bad in math). This can make it very hard to reimplement the analysis and reproduce the results, thereby decreasing the incentive to do so for others. Having the original code of the authors could clarify things a lot in those situations. I think reproducibility would benefit more from having the code and tolerate potential bugs, than hoping for someone to dig through the methods part and reimplement it.

Concerning @rougier 's comment 2: I fully agree again, but I have never seen someone replicate all results of an entire paper. You are the first example I know of. But since you are planning to consider [Part:] submissions, I think this issue is settled anyway. 

My intention is to make research more reproducible since the current state is not acceptable. I worry, that ReScience might just  end up with submissions that reproduce results of papers which were easy to reproduce in the first place, instead of increasing the general reproducibility of research. I think it could do better in that respect by dropping the non-author requirement. This was my motivation to raise this issue. You might envision a different scope of ReScience and that's fine. I just wanted you to consider the benefits of it.

**Comment by ctb** [comment]
While I appreciate @ThomasA's point, I think @fabiansinz is completely correct.  I publish the code for my papers along with the papers themselves, but the reviewers never seem to look at the code; this would be a venue for peer review of the analysis code.

**Comment by rougier** [comment]
@fabiansinz ReScience cannot fix the whole reproducibility problem on its own. I agree with most for your arguments but still, ReScience may not  be the place to do that yet. I'm not saying that things won't change in the future, but until we get some submissions, it might be better to keep ReScience focused. 

@ctb Yes, but I fear this won't be the case anytime soon. Reviewing code is hard, especially for an original research where readability is not the main point. But when a paper is replicated, we can expect better code (at least) and more or less easier control of the code regarding expected results.

**Comment by pdebuyl** [comment]
Hi all,

I see points on both sides. Still, one of the arguments is that replication by *someone else* is a much stronger validation. Given the young age of the journal, it makes sense to try this model (i.e. keep the current guideline) first. There is a gap in the publication system right now and the goals of ReScience fill one of them.

**Comment by fabiansinz** [comment]
@rougier I can see your point. Would be great if you keep it in mind for possible future changes.

**Comment by rougier** [comment]
For sure. I hope we'll be able to come back to all suggestions 6 months from now and think again on how to handle them.

**Comment by fabiansinz** [comment]
Good luck and a good start for the journal until then. Again, +1 for starting it.

**Comment by rougier** [comment]
Thanks.
