### ISSUE TITLE
Referencing and visibility of ReScience's articles

### ISSUE THREAD

**Issue by MehdiKhamassi** [ReScience/ReScience#20]
There appears to be a problem in the way google scholar recognizes the authors and the title of the first article published in ReScience (Topalidou and Rougier 2015) : https://scholar.google.fr/scholar?hl=en&q=author%3Azito+author%3Akhamassi&btnG=&as_sdt=1%2C5&as_sdtp=
Google scholar thinks that Tiziano, Benoît and I are the authors and that "Meropi Topalidou ... Nicolas Rougier ..." is the title of the article.
Apparently, Google scholar extracted this information from the pdf which was uploaded on researchgate.

Do you think we could solve this by adding meta-data in the PDF of each article published in ReScience so that Google parses it correctly?

**Comment by rougier** [comment]
Thanks. You're right.

We need to integrate metadata in the template as explained here:
http://tex.stackexchange.com/questions/26529/how-can-i-generate-pdf-metadata-from-latex

**Comment by rougier** [comment]
Fixed. See https://github.com/ReScience/ReScience-submission/commit/f966cb55fbe4252751f0f49c51cce59d1b1699ac
