### ISSUE TITLE
Do we need some conditions for reviewers ? (no)

### ISSUE THREAD

**Issue by rougier** [ReScience/ReScience#26]
A message has been posted (by me) on twitter saying any PhD or PhD-student can be reviewer.
What about master or grad students ? Is there any reason to not have them on board ? Do we need any conditions at all ?

I personally think that to properly make a review you need some knowledge of the scientific field to appreciate to what extent the original paper has been replicated or not. It means a reviewer should be able to read and understand the original paper as well as the new one.

**Comment by mr-c** [comment]
FYI, I do not have an advanced degree, nor do I currently plan to get one; I have reviewed several bioinformatics papers by invitation and will continue to do so. It is not likely that any one reviewer can be an expert on all aspects of a given paper, so please don't exclude those of us who have something to contribute but don't have traditional credentials. Cheers.

**Comment by pdebuyl** [comment]
"Or equivalent experience". This remains very much an editorial power. Given the open character of ReScience, I believe that this power will be used wisely.

**Comment by ctb** [comment]
What @mr-c said :).

A good criterion might be that the primary reviewer have a record of publication or other scientific contribution (source code, for example). But usually it's up to the handling editor to decide, and I think that discretion should be preserved.

**Comment by mr-c** [comment]
(on a side note, I quite like the idea of having reviewers be explicit about their expertise, confidence levels, and what their review does and does not cover. That would make room for non-academics to make meaningful contributions)

**Comment by tpoisot** [comment]
:+1: to what @mr-c said. I think a good mix would be one reviewer with field knowledge, and another reviewer who knows the tools and computational aspects. Ideally both reviewers would have both, but I wouldn't put a requirement based on degrees held or anything else.

**Comment by tpoisot** [comment]
Roy Soc Interfaces has two mandatory fields for reviewers: what is your expertise relative to this paper, and what part of the paper do you not feel qualified to comment on. I think this is a good model to emulate.

**Comment by khinsen** [comment]
Since we do open reviewing, reviewer incompetence is unlikely to be a problem; few people would be comfortable exposing their incompetence publicly in GitHub. Until this actually happens, I propose we don't impose any criteria for reviewers, but just remind them that they should stay within their competence.

In the end it's always the editor(s) who decide, so in the unlikely event that we get a low-level review, the editor(s) can simply decide to ignore it.

I'd be more in favor of taking the opposite approach of encouraging everyone to become a reviewer and propose guidance to those who are not (yet) at ease with this.

**Comment by rougier** [comment]
I just opened an issue for people to inform us they want to be reviewer: https://github.com/ReScience/ReScience/issues/27.

Nothing needed but a github account and a one line description. Please advertise the link !
