### ISSUE TITLE
Docker environment

### ISSUE THREAD

**Issue by EHadoux** [ReScience/ReScience#31]
Hello,

should we encourage the submitters to give a dockerfile alongside theirs submission in order to facilitate the work of the reviewers (no installation other than docker, no package conflicts, no OS limitation, etc.).

For more information: [Docker](https://docs.docker.com/engine/understanding-docker/)

**Comment by rougier** [comment]
It might be an option yes, but submitter should also give a complete description of their environment alongside I think.

**Comment by EHadoux** [comment]
Absolutely, it's not mutually exclusive. A Dockerfile is a comprehensive description though.

**Comment by khinsen** [comment]
Submitting dockerfiles is fine with me, if it's in addition to a human-readable description of the environment. Dockerfiles are like code - comprehensive but based on implicit information (Docker itself, the base image, ...) that a human reader is not necessarily aware of. We ask for papers explaining the ideas behind the code, so we should also ask for a human-readable exaplanation of a Dockerfile.

The real question for me is: what do we expect reviewers to do? Check the explicit installation instructions, even if there's a Dockerfile? Test-run the Dockerfile, ignoring the manual installation instructions? Check both?

**Comment by EHadoux** [comment]
You are right, that's why I proposed to have both.
However, I think we are reviewing here the manual code and the outputs, not the way to run it, do we? Do we care if the submitter is using this library or this other ? (Genuine question) I mean, if yes, it amounts to check the reproducibility of such a lib and could end up to a quick deep recursion.

**Comment by khinsen** [comment]
Reviewers are expected to check if they can run the code and get the same results (see our [reviewing guidelines](https://rescience.github.io/edit/), which implies that they do an installation first. We don't suggest any particular way to install code for now, but it seems logical to use the paper's instructions, except for stuff you already have on your machine.

**Comment by remram44** [comment]
I think you should encourage people to submit a description that have enough details for reproducibility. Making a Dockerfile mandatory is probably not necessary (and in fact does not guarantee reproducibility -- archiving the Docker image would) but including the precise versions of dependencies used (something like a pip requirement file, or Anaconda environment file, ...) would certainly be a good move!

I see for example here: https://github.com/RafaelNH/ReScience-submission/tree/RNH-AR-EG-SSTJ-ETP-MMC-2016/code
> After installing the dependencies of step 3, Dipy can be installed by typing in the terminal "pip install dipy".

Including a version number as `pip install dipy==0.11.0` is a low hanging fruit, or better yet this requirements file:
```
dipy==0.11.0
nibabel==2.1.0
numpy==1.11.2
```
My two cents -- keep up the good work!

**Comment by benureau** [comment]
@remram44: yes indeed. "The code was run with numpy 1.11.2" It is more useful, in a scientific context, than "The code is compatible with numpy 1.10.x and above", as @rougier and I are arguing in a paper that will be finished shortly. A even better option is to include this information automatically *in the output files* (with a git hash, a timestamp, and a description of the platform). I am currently working on a package for python that would do exactly that, with minimal involvement of the user.

**Comment by pdebuyl** [comment]
A first step in the direction outlined here (not Docker, but significant description) is already part of our guidelines, see the list at the bottom of the [write](http://rescience.github.io/write/) page and the [platform](http://rescience.github.io/platform/).

The language encourages to include also library information and a "full" example is only given for Python and C. Beyond that, it is up to the reviewers to make sure the information is complete.
