### ISSUE TITLE
Suggesting a paper to replicate?

### ISSUE THREAD

**Issue by ACompNeuroscientist** [ReScience/ReScience#37]
There are two highly cited computational papers from the same author which I have been unable to reproduce, despite great effort.  However, there are two problems:

1) My attempts to reproduce them were in Matlab and I am less skilled with Python.  As a new faculty member, it would be impossible to find the time to learn Python enough to attempt a replication in Python.

2) As an untenured faculty member in the same field, I am hesitant to attach my name to a replication attempt if the results are deemed not reproducible.

This gives rise to two questions:
1) Can I suggest papers for replication, so that someone with better Python skills can try it out?

2) Can papers that fail to reproduce a result be submitted anonymously?

To be clear, I am completely open to the possibility that the results in those papers are reproducible and the mistake is mine.  This is another reason I would be eager to suggest the paper for someone else to try.

I would be happy to donate to the ReScience project (if donations are accepted) or perform some needed service at ReScience in return for someone attempting a replication of the papers.

**Comment by ACompNeuroscientist** [comment]
I suppose I might as well post one of the papers:

"Emergence of Complex Computational Structures From Chaotic Neural Networks Through Reward-Modulated Hebbian Learning"

http://cercor.oxfordjournals.org/content/24/3/677.short

I implemented the model and it correctly produced the target outputs, but the weights did not converge.

For the other paper, I will more thoroughly verify my implementation of the model before posting it.

**Comment by benureau** [comment]
From the [Rescience FAQ](https://rescience.github.io/faq/):


> What if I fail to replicate a research result?
> 
> Some research may not be replicable. Before declaring a research result non-replicable, we require extra caution to be taken. In addition to scrutiny of your submission by reviewers and editors, we will contact the authors of the original research, and issue a challenge to the ReScience community to spot and report (using the issue tracker) errors in your implementation. If no errors are found, your work will be accepted and the original research will be declared non-replicable.
> 

Just to clarify the situation: did you contact the authors about being unable to replicate? About them providing you with code or even a binary showing that the results are indeed replicable (versus reproducible, as defined in the FAQ)?

**Comment by rougier** [comment]
Concerning the possibility of proposing paper to be replicated, yes, this is something we should do but need to find a the best way to have an up-to-date list and to let people know when someone wants to replicate a paper (just to avoid having several people working on the same replication).

Concerning non-replicaable paper, we did not have the case yet mostly because people are a bit afraid of publishing a paper saying another paper cannot be replicated (private communication). If you're tenured, that might be easier but I perfectly understand your hesitation. The other problem is to be able to build strong evidence the original paper cannot be replicated. We explain in the FAQ that this would need extra precaution (3 reviewers + contact with the original author(s) if possible).

Anonymous publication could be an option but I don't know what would be the legal aspects. It also depends if you want to stay totally anonymous (I mean even from the editorial board) or not.

Are you aware of scientific journals publishing officially anonymous article ?

**Comment by khinsen** [comment]
I haven't seen anonymous scientific papers yet, but some journals do allow the use of pseudonyms, which comes down to the same. We don't check anyone's identity here anyway, so if someone makes a submission using a pseudonym, I suspect nobody would notice.

I like the idea of suggesting papers for replication. The logical next step is collaborative replication work, in the open on GitHub.

**Comment by rougier** [comment]
I've been talking with @benureau and he proposed a nice solution that would be to have a new repository (e.g. `ReScience/call-for-replication`) where people would open one issue per suggestion and this issue would be the place to discuss the paper (reason to propose, difficulty, etc.). This issue would be closed once the challenge has been accepted by someone (such that people knowns some other people are already working on that). We could also ask people to not suggest their own work and to suggest themselves as reviewers (but nothing mandatory of course).

Concerning the use of pseudonym, we still need some name to put in the PDF paper.  But we could also use a generic pseudonym for such a case. One potential problem is how authors declare such publication in their CV (if they want to) ?

**Comment by benureau** [comment]
Declaring such a publication in their CV is clearly incompatible with remaining anonymous. But indeed, there should be a mechanism to deanonymize replications.

I assume that people will create anonymous github accounts to submit anonymous replication to ReScience. Assuming they remain in control of this accounts, they could then use them to ask for deanonymizing the publication at a latter date. We would just need to update the PDF paper. Another solution is to use encryption to embed the author's name into the PDF in an unidentifiable way (but that feel a bit spycrafty to me). 

I feel like we should consider if asking that authors of anonymous replications reveal their name to at least someone in the board of ReScience might be a good idea. That would decrease the temptation of anonymous self-replication, and identify potential conflicts of interest.

**Comment by pdebuyl** [comment]
Thinking of the implication of the process, I think that we could proceed like regular journals for this, but in a more open and transparent manner (see the experience here http://www.untruth.org/~josh/How_to_Publish_a_Comment.pdf ).

For instance, publishing the paper "as usual" and then proposing a right of reply to the un-replicable authors, requiring indeed the same level of quality as for other rescience papers.

The biggest problem I could imagine with anonymous submissions is if the unreplicable authors start a vendetta on the journal :-)

**Comment by khinsen** [comment]
I agree with @benureau that the identity issue can mostly be handled via the GitHub account, meaning that it's not our problem.

I don't expect authors anonymously replicating their own non-replicable papers to be a major issue. Once a ReScience paper becomes a must-have on everyone's CV, we can reconsider. Of course it would be nice if the editorial board could be informed about an author's true identity, but not even GitHub knows the true identity of account owners, so I don't see how we could do any better.

**Comment by rougier** [comment]
@ACompNeuroscientist I just created the [call for replication](https://github.com/ReScience/call-for-replication) repository. You can now open an issue in this repository such that people know there is an interest in having this article replicated.

**Comment by benureau** [comment]
@rougier It may be useful to create an issue template (https://github.com/blog/2111-issue-and-pull-request-templates) for this repository so that important details about the article and the reason why it is interesting to replicate it, how hard it is expected to be, etc., are present when people submit an replication call. I create a pull request for that (https://github.com/ReScience/call-for-replication/pull/1).
