### ISSUE TITLE
Replication and High Performance Computing

### ISSUE THREAD

**Issue by mkloczko** [ReScience/ReScience#41]
I would like to ask whether it is possible to submit work related to benchmarks on multi-core architectures. Would replicability be an issue here ?

**Comment by rougier** [comment]
It's hard to answer without some more details. It may depends if the reviewer of your replicatino needs to have access to a specific hardware. Do you have a specific paper in mind ?

**Comment by mkloczko** [comment]
The work I have in mind is about measuring scalability of a heuristic program. The program tries to find the global minima of a function on a machine with 64 cores. An example of an article which tackles the problem is [Highly Scalable Erlang Framework
for Agent-based Metaheuristic Computing](http://www.sciencedirect.com/science/article/pii/S1877750316300242).

**Comment by mkloczko** [comment]
I see. Thank you!
