### ISSUE TITLE
Request version information

### ISSUE THREAD

**Issue by pdebuyl** [ReScience/ReScience#42]
A full version information could be requested in the paper or the README of the code directory.

Example for Python

```py
import sys
import numpy as np
import scipy

print("Platform:", sys.platform)
print("Python:", sys.version)
print("NumPy:", np.version.version)
print("SciPy:", scipy.version.version)
```

    Platform: linux
    Python: 3.5.2+ (default, Sep 22 2016, 12:18:14)
    [GCC 6.2.0 20160914]
    NumPy: 1.12.0b1
    SciPy: 0.17.0

Example for C

```
pierre@pc$ uname -mosv
Linux #1 SMP Debian 3.16.7-ckt9-3 (2015-04-23) x86_64 GNU/Linux
```

```
pierre@pc$ gcc --version
gcc (Debian 6.2.0-5) 6.2.0 20160927
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The version used by the reviewers could be appended.

**Comment by pdebuyl** [comment]
Ok, I will propose a PR to the rescience website soon. I'll close this issue then, I leave it open for now in case others want to comment.

**Comment by rougier** [comment]
You can also modify the PR template for submission to explain to not forget to add dependencies/versions

**Comment by pdebuyl** [comment]
Here's an example https://github.com/pdebuyl-lab/colloidal_chemotaxis_companion/blob/master/README.md

Any comments?

**Comment by khinsen** [comment]
@pdebuyl This looks very good, at least in theory (meaning that I did not try to re-run anything).

A suspect point: "The Python code is provided in Jupyter notebooks." There are no notebook in the repository. Perhaps simply "not yet". I wanted to look at them to see if the Python dependency list is complete. In particular because I don't see matplotlib, which most notebooks I see use in some way.

**Comment by pdebuyl** [comment]
The notebooks are being prepared here: https://github.com/pdebuyl/compute/tree/master/chemotactic_cell

Thinking of it, I should not only add matplotlib but also h5py even though I hope very much that any specific version of h5py produces the same output. Ok, done also :-)

**Comment by pdebuyl** [comment]
Since the discussions, I added the line about "platform instructions" in the author's guidelines.

People seem to use it in recent submissions also, even though I am not certain that all editors know about this.

I propose to close anyway, as the instructions are there.
