### ISSUE TITLE
Criteria for publication 

### ISSUE THREAD

**Issue by SepehrMN** [ReScience/ReScience#46]
Under criteria for publication, it is written "You cannot submit the replication of your own research, nor the research of your close collaborators."

The first part is clear.

We have replicated a 20-year-old study in a modern language without seeing the original implementation and the precise algorithms. The first author of the paper wrote all the code and prepared the figures, but we do not know him. I have not met the other authors. The second and third authors will provide ideas on future directions of a related project but we will write the code and tools. Can we please submit our contribution?

**Comment by khinsen** [comment]
I am not sure I understand the situation correctly. The authors you cite are those of the replication, right? Not the original paper? Then what exactly is the overlap between the authors of the original paper and the authors of the replication?

**Comment by SepehrMN** [comment]
Many thanks @khinsen. I have discussed this and will submit it as a single author paper.
