### ISSUE TITLE
page numbers

### ISSUE THREAD

**Issue by pdebuyl** [ReScience/ReScience#47]
Hi @rougier @khinsen 

So, we do not have page numbers? Just asking because I am preparing the files for Henriques et al. I know it seems a lowly thought but most citations styles will have a slot with page numbers, journal typesetters (whatever that means by now) will ask, etc.

So the full references is year, volume, issue? (+ name of authors to make papers distinct)

**Comment by khinsen** [comment]
Some journals have switched from page numbers to article numbers with the transition to electronic publishing. That could be a solution for us as well: we simply number the articles inside an issue. And we can even do this retroactively to provide "complete" citations for everyone.

**Comment by pdebuyl** [comment]
Indeed. I concur!

**Comment by pdebuyl** [comment]
So, I propose to number the items in order of DOI assingment until now. For coming articles, we need a kind of protocol because two editors might run into assigning a DOI on, say, the same day, and input the same article # to two papers. A [GIL](https://en.wikipedia.org/wiki/Global_interpreter_lock) via the editors-in-chief seems the simplest and, given our traffic, reasonable option.

**Comment by pdebuyl** [comment]
On the technical side, there is one metadata line to add to the `.md` article file and one inclusion of `$Publication.issue` in `rescience-template.tex`.

There is no formal decision process so I'll wait approval by @rougier and @khinsen before submitting a PR.

**Comment by pdebuyl** [comment]
@rougier ?

**Comment by pdebuyl** [comment]
Final point of procedure: either @khinsen or @rougier gives the article number on the review issue of the https://github.com/ReScience/ReScience-submission repo

**Comment by pdebuyl** [comment]
Please assign article numbers to the 2017 papers as a start.

- Shifman: article 1 https://github.com/ReScience/ReScience-submission/pull/22
- Henriques: article 2 https://github.com/ReScience/ReScience-submission/pull/26

(I am waiting for this to publish Henriques et al, ReScience **3**(1), 2 (2017), doi coming.

**Comment by rougier** [comment]
Sorry, I've been busy. Ok for the metadata in the template (shoudl have done this a long time ago).
What's the deal with article number (I'm not sure I got the point).

**Comment by pdebuyl** [comment]
Mmmmh, "What's the deal with article number (I'm not sure I got the point)." there is no deal :-) I believe that it makes better citation data but that's it.

**Comment by rougier** [comment]
Sorry @pdebuyl, I was a bit tired and my question was ill-posed. I meant, what do you propose exactly, but after reading more carefully I understood you propose to have number on each article, is that right ?

@khinsen For the retroactive numbers, that might be more difficult because we would need to re-issue DOI for each articles, no ?

**Comment by pdebuyl** [comment]
Hi @rougier no problem for yesterday :-)

You can see an example here (proofreading stage) https://github.com/ReScience-Archives/Henriques-Rokem-Garyfallidis-St-Jean-Peterson-Correia-2017/tree/master/article

What can be done is anyway to number the articles on the page http://rescience.github.io/read/ so that citation is easier. Probably the *metadata* on Zenodo can be updated on the existing DOIs.

The DOI do not appear *in* the pdfs as of now. So the citation info is retrieved via the ReScience table of contents or the Zenodo metadata anyway.

**Comment by rougier** [comment]
You're right and I might be still tired actually :)

But for new published papers, article number will appear in the PDF, right ?

For future papers, we could also try to have the DOI inside the paper. I think we can reserve a DOI on Zenodo but this needs to be checked. And if this is too much trouble, we can leave it as it is.

**Comment by pdebuyl** [comment]
> But for new published papers, article number will appear in the PDF, right ?

Yes, that was the point of my update of the template. See Henriques 2017 :-)
