### ISSUE TITLE
Article number request

### ISSUE THREAD

**Issue by pdebuyl** [ReScience/ReScience#48]
This thread is for editors to register article numbers at the final stage of publication.

**Comment by pdebuyl** [comment]
I claim Volume 3, Issue 1, Number 2 for Henriques et al https://github.com/ReScience/ReScience-submission/pull/26

**Comment by rougier** [comment]
I claim Volume 3, Issue 1, Number 3 for [Rostami et al (PR #24)](https://github.com/ReScience/ReScience-submission/pull/24)

**Comment by ThomasA** [comment]
I claim Volume 3, Issue 1, Number 4 for Ruogier 2017 (ReScience/ReScience-submission#28)

**Comment by khinsen** [comment]
I claim Volume 3, issue 1, Number 5 for [Stollmeier 2017](https://github.com/ReScience/ReScience-submission/pull/27#issuecomment-324297105)

**Comment by oliviaguest** [comment]
I claim Volume 3, issue 1, Number 7 for [Metzner 2017](https://github.com/ReScience/ReScience-submission/pull/30)

**Comment by otizonaizit** [comment]
I claim Volume 3, issue 1, Number 7 for [Detorakis 2017](https://github.com/ReScience/ReScience-submission/pull/35)

**Comment by rougier** [comment]
I claim Volume 3, issue 1, Number 8 for [Stojic 2017](https://github.com/ReScience/ReScience-submission/pull/36)

**Comment by benoit-girard** [comment]
I claim Volume 3, issue 1, Number 9 for [Diem 2017](https://github.com/ReScience/ReScience-submission/pull/33).

**Comment by rougier** [comment]
I claim Volume 4, issue 1, Number 1 for [Caze Stimberg Girard 2018](https://github.com/ReScience/ReScience-submission/pull/45)

**Comment by otizonaizit** [comment]
I claim volume 4, issue 1, Number 3 for [Senden Schuecker Hahne Diesmann Goebel 2018](https://github.com/ReScience/ReScience-submission/pull/46)

**Comment by ctb** [comment]
I claim volume 4, issue 1, Number 4 for [Mondeel Ogundipe Westerhoff 2018](https://github.com/ReScience-Archives/Mondeel-Ogundipe-Westerhoff-2018).

**Comment by rougier** [comment]
I claim volume 4, issue 1, Number 6 for [Hathway Goodman 2018](https://github.com/ReScience/ReScience-submission/pull/51)

**Comment by karthik** [comment]
I claim volume 4, issue 1, Number 6 for [Poisot 2018](https://github.com/ReScience/ReScience-submission/pull/39)

**Comment by rougier** [comment]
@karthik you should claim number 7

**Comment by karthik** [comment]
Sorry that was a typo. I’ll edit my comment

**Comment by pdebuyl** [comment]
I claim Volume 5, Issue 1, Number 1, for Caron, Lessard, Wu, Poisot 2019 https://github.com/ReScience/ReScience-submission/pull/50

**Comment by benoit-girard** [comment]
I claim Volume 5, Issue 1, Number 2, for Tennøe et al., 2019,  https://github.com/ReScience/ReScience-submission/pull/53

**Comment by khinsen** [comment]
I claim Volume 5, Issue 3, Number 1 for Sukhoy and Stoytchev, https://github.com/ReScience/submissions/issues/6

**Comment by gdetor** [comment]
I claim Volume 5, Issue 3, Number 2 for Larisch, https://github.com/ReScience/ReScience-submission/pull/57#

**Comment by oliviaguest** [comment]
I claim Volume 5, Issue 3, Number 3 for https://github.com/ReScience/submissions/issues/7

**Comment by khinsen** [comment]
I claim Volume 6, Issue 1, Number 1 for https://github.com/ReScience/submissions/issues/11.

Note that issue 1 is for the [Ten Years Reproducibility Challenge](https://github.com/ReScience/ten-years). Other articles in 2020 should go into volume 6, issue 2.

**Comment by khinsen** [comment]
I claim Volume 6, Issue 1, Number 2 for https://github.com/ReScience/submissions/issues/22.

**Comment by rougier** [comment]
I claim Volume 6, Issue 3, Number 1 for https://github.com/ReScience/submissions/issues/9

**Comment by khinsen** [comment]
I claim Volume 6, Issue 1, Number 3 for https://github.com/ReScience/submissions/issues/12

**Comment by khinsen** [comment]
I claim Volume 6, Issue 1, Number 5 for https://github.com/ReScience/submissions/issues/14

**Comment by oliviaguest** [comment]
I claim Volume 6, Issue 3, Number 2 for ReScience/submissions#29

**Comment by otizonaizit** [comment]
I claim Volume 6, Issue 1, Number 6 for https://github.com/ReScience/submissions/issues/32

**Comment by otizonaizit** [comment]
I claim Volume 6, Issue 1, Number 7 for https://github.com/ReScience/submissions/issues/20

**Comment by rougier** [comment]
I claim Volume 6, issue 1, Number 8 for https://github.com/ReScience/submissions/issues/19

**Comment by pdebuyl** [comment]
I claim Volume 6, issue 1, Number 9 for https://github.com/ReScience/submissions/issues/33

**Comment by rougier** [comment]
I claim Volume 6, issue 1, Number 10 for https://github.com/ReScience/submissions/issues/23#issuecomment-646762988

**Comment by pdebuyl** [comment]
I claim Volume 6, issue 1, Number 11 for https://github.com/ReScience/submissions/issues/41

**Comment by karthik** [comment]
I claim Volume 6, issue 1, Number 12 for ReScience/submissions#18

**Comment by oliviaguest** [comment]
I claim Volume 6, issue 1, Number 13 for ReScience/submissions#25

**Comment by otizonaizit** [comment]
I claim Volume 6, issue 1, Number 14 for https://github.com/ReScience/submissions/issues/37

**Comment by oliviaguest** [comment]
I claim Volume 6, Issue 3, Number 3 for ReScience/submissions#30

**Comment by oliviaguest** [comment]
I claim Volume 6, Issue 3, Number 4 for ReScience/submissions#10

**Comment by rougier** [comment]
I claim Volume 6, Issue 3, Number 5 for https://github.com/ReScience/submissions/issues/15

**Comment by rougier** [comment]
I claim Volume 6, Issue 1, Number 15 for https://github.com/ReScience/submissions/issues/16

**Comment by gdetor** [comment]
I calim Volume 6, Issue 1, Number 16 for [ReScience/submissions#35](https://github.com/ReScience/submissions/issues/35)

**Comment by otizonaizit** [comment]
I claim Volume 6, Issue 3, Number 6 for https://github.com/ReScience/submissions/issues/45

**Comment by koustuvsinha** [comment]
I claim Volume 6, Issue 3, Number 7 for https://github.com/ReScience/submissions/issues/44

**Comment by ThomasA** [comment]
I claim Volume 6, Issue 1, Number 17 for https://github.com/ReScience/submissions/issues/27

**Comment by khinsen** [comment]
I claim Volume 6, Issue 1, Number 18 for https://github.com/ReScience/submissions/issues/21

**Comment by rougier** [comment]
I claim Volume 6, Issue 3, Number 8 for https://github.com/ReScience/submissions/issues/10

**Comment by benoit-girard** [comment]
I claim Volume 6, Issue 1, Number 19 for ReScience/submissions#28

**Comment by benoit-girard** [comment]
I claim Volume 7, Issue 1, Number 1 for https://github.com/ReScience/submissions/issues/8

**Comment by benoit-girard** [comment]
I claim Volume 6, Issue 1, number 20 for https://github.com/ReScience/submissions/issues/39

**Comment by rougier** [comment]
I claim I claim Volume 6, issue 1, Number 21 for https://github.com/ReScience/submissions/issues/40

**Comment by rougier** [comment]
I claim Volume 7, Issue 1, Number 2 for https://github.com/ReScience/submissions/issues/47

**Comment by rougier** [comment]
I claim Volume 7, Issue 1, Number 3 for ReScience/submissions#52

**Comment by eroesch** [comment]
I claim Volume 7, Issue 1, Number 4 for [ReScience/submission#17](https://github.com/ReScience/submissions/issues/17)

**Comment by koustuvsinha** [comment]
I claim Volume 7, Issue 2, Numbers 1-24 for [ML Reproducibility Challenge 2020](https://github.com/ReScience/RC-2020/)

**Comment by rougier** [comment]
I claim Volume 7, Issue 1, Number 5 for https://github.com/ReScience/submissions/issues/46

**Comment by oliviaguest** [comment]
I claim Volume 7, Issue 1, Number 6 for ReScience/submissions#53

**Comment by khinsen** [comment]
I claim Volume 7, Issue 1, Number 7 for https://github.com/ReScience/submissions/issues/55

**Comment by rougier** [comment]
I claim Volume 6 Issue 1, Number 22 for https://github.com/ReScience/submissions/issues/34

**Comment by khinsen** [comment]
I claim Volume 7, Issue 1, Number 8 for https://github.com/ReScience/submissions/issues/54

**Comment by eroesch** [comment]
I claim Volume 7, Issue 1, Number 9 for [ReScience/submission#49](https://github.com/ReScience/submissions/issues/49)

**Comment by rougier** [comment]
I claim Volume 7, Issue 1, Number 10 for https://github.com/ReScience/submissions/issues/56

**Comment by benoit-girard** [comment]
I claim Volume 7, Issue 1, Number 11 for https://github.com/ReScience/submissions/issues/50

**Comment by D-Maurel** [comment]
I claim Volume 7, Issue 1, Number 12 for https://github.com/ReScience/submissions/issues/48

**Comment by oliviaguest** [comment]
I claim Volume 7, Issue 1, Number 12 for https://github.com/ReScience/submissions/issues/48

**Comment by gdetor** [comment]
I claim volume 7, Issue 1, Number 13 for ReScience/submissions#51

**Comment by rougier** [comment]
@gdetor We are now on volume 8 (see https://rescience.github.io/read/), such that you should claim colume8, issue 1, number 2 I think.

**Comment by gdetor** [comment]
I claim volume 8, Issue 1, Number 2 for ReScience/submissions#51

**Comment by pdebuyl** [comment]
I claim volume 8, Issue 1, Number 3 for https://github.com/ReScience/submissions/issues/58

**Comment by koustuvsinha** [comment]
I claim Volume 8, Issue 2, Numbers 1-49 for the ML Reproducibility Challenge. @rougier let me know if it is okay to open a new Issue for this.

**Comment by rougier** [comment]
49 articles! Do you think it's worth to split them in two (or more) issues if you have some criterion for splitting?

**Comment by rougier** [comment]
And yes, maybe opening an issue giving relevant information would be nice.

**Comment by rougier** [comment]
I claim volume 8, Issue 1, Number 4 for https://github.com/ReScience/submissions/issues/62

**Comment by khinsen** [comment]
I claim volume 8, Issue 1, Number 5 for https://github.com/ReScience/submissions/issues/13

**Comment by rougier** [comment]
I claim volume 8, issuer 1, Number 6 for https://github.com/ReScience/submissions/issues/61

**Comment by rougier** [comment]
I claim volume 9, issue 1, numbe 1 for https://github.com/ReScience/submissions/issues/59

**Comment by koustuvsinha** [comment]
I claim volume 9, Issue 2, numbers 1 to 45 for [MLRC 2022](https://paperswithcode.com/rc2022)

**Comment by rougier** [comment]
I claimer volume 9, issue 1, number 2 for https://github.com/ReScience/submissions/issues/64

**Comment by rougier** [comment]
I claim volume 9, issue 1, number 3 for https://github.com/ReScience/submissions/issues/72#issuecomment-1839377679

**Comment by rougier** [comment]
Here it is: https://zenodo.org/record/10257800. It'll appear soon the journal website.

**Comment by rougier** [comment]
I claim volume 9, issue 1, number 4 for https://github.com/ReScience/submissions/issues/66

**Comment by eroesch** [comment]
I claim volume 9, issue 1, number 5 for [ReScience/submissions#60](https://github.com/ReScience/submissions/issues/60)

**Comment by rougier** [comment]
I claim volume 9, issue 1, number 6 for [ReScience/submissions#73](https://github.com/ReScience/submissions/issues/73)

**Comment by gdetor** [comment]
I claim volume 9, issue 1, number 7 for https://github.com/ReScience/submissions/issues/75

**Comment by rougier** [comment]
@gdetor Since we're in 2025, this is now volume 10,  issue 1, number 1 for  https://github.com/ReScience/submissions/issues/75

**Comment by rougier** [comment]
I claim volume 10, issue 1, number 2 for https://github.com/ReScience/submissions/issues/85

**Comment by rougier** [comment]
I claim volume 10, issue 1, number 3 for https://github.com/ReScience/submissions/issues/74

**Comment by rougier** [comment]
I claim volume 10, issue 1, number 4 for https://github.com/ReScience/submissions/issues/89

**Comment by rougier** [comment]
I claim volume 10, issue 1, number 5 for  https://github.com/ReScience/submissions/issues/87

**Comment by rougier** [comment]
I claime volume 10, issue 1, number 6 for https://github.com/ReScience/submissions/issues/90

**Comment by rougier** [comment]
I claime volume 11, issue 1, number 1 for https://github.com/ReScience/submissions/issues/93

**Comment by rougier** [comment]
I claime volume 11, issue 1, number 2 for https://github.com/ReScience/submissions/issues/86

**Comment by khinsen** [comment]
I claim volume 11, issue 1, number 3 for https://github.com/ReScience/submissions/issues/96
