### ISSUE TITLE
Publication support

### ISSUE THREAD

**Issue by ThomasA** [ReScience/ReScience#52]
I am in the process of handling my first replication as editor (@rougier's ReScience/ReScience-submission#28). Reading the [editor guidelines](http://rescience.github.io/edit/), I get a bit in doubt about the recommended procedure for inclusion into ReScience-Archives.
It says to:
> * Import the authors’ repository into the ReScience archives (https://github.com/ReScience-Archives) using the naming convention “Author(s)-YEAR”
> * Add a new remote (named rescience) in your local copy of the repository that points to the newly imported repository (the one on ReScience-Archives)

1. Firstly, @rougier's repo is a fork of ReScience/ReScience-submission in which 'master' contains the boilerplate template and the branch 'rougier-2017' contains the replication. Is it really the intention to import the forked author repo, including the not-so-useful 'master' branch (and the seemingly outdated branch 'topalidou-rougier') into the new ReScience-Archives repo?
2. In *Add a new remote* etc. I am a bit in doubt which repos are referred to. I assume *your local copy of the repository* is my local copy of rougier/ReScience-submission? And in this local repo I add a new remote pointing to the newly created ReScience-Archives/Rougier-2017?

Later, the editor guidelines state:
> * Merge the rescience branch into master
> * Push these changes onto the rescience remote repository

1. Does *the rescience branch* correspond to the 'rougier-2017' branch in rougier/ReScience-submission? In that case, the merge would correspond to merging the 'rougier-2017' branch into 'master' in rougier/ReScience-submission - sort of overwriting the boilerplate template found there.
2. Does *Push these changes* then refer to the resulting content of 'master' in rougier/ReScience-submission? Which should be pushed onto which branch in ReScience-Archives/Rougier-2017? This does not make much sense to me since ReScience-Archives/Rougier-2017 is assumed to already contain rougier/ReScience-submission by the initial import.

The following would make a lot more sense to me instead:

1. Clone a local copy of rougier/ReScience-submission. The following takes place in that local copy; let us call it 'author-local'.
2. Checkout the 'rougier-2017' branch.
3. Fix what needs fixing (re-generate PDF etc.).
4. Create a new public, empty repository ReScience-Archives/Rougier-2017.
5. Add ReScience-Archives/Rougier-2017 as a new remote 'rescience' in the 'author-local' repo.
6. Push the branch 'rougier-2017' to 'rescience/master'.

Surely, I must have missed the point somewhere. Please advise.

**Comment by pdebuyl** [comment]
Hi @ThomasA 

There is room for a bit of intrepretation, as many authors will have worked as @rougier in a named branch. What I did was
1. Do the "import"
2. Clone the imported version and overwrite "master" by the author's branch
3. Work on that copy for all the file renaming etc and push directory to ReScience-Archives/AUTHORNAME-2017 master

**Comment by ThomasA** [comment]
@pdebuyl that sounds operational but why import in the first place at all instead of pushing only the author's branch to an initially empty repository? Also, I do not understand why we would want the author's branch 'topalidou-rougier', which is not part of what was reviewed, in the archive?

**Comment by rougier** [comment]
When it's written merging branch into master, we are talking about the repository in the ReScience-Archives. The idea is to have a clean repository without any branch that point directly to the work.

**Comment by rougier** [comment]
@ThomasA oh, can we do that ?

**Comment by ThomasA** [comment]
@rougier AFAIK. I can test the procedure i proposed in the original question if you like?

**Comment by pdebuyl** [comment]
@ThomasA Your version is a bit cleaner but overall the end result is the same except for possible extra branches in the archive that you can delete. I believe there are less clicks and git instructions in my version though :-)

**Comment by rougier** [comment]
@pdebuyl By the way, https://github.com/ReScience-Archives/Henriques-Rokem-Garyfallidis-St-Jean-Peterson-Correia-2017 has two branches. Did you forget to merge into master ?

**Comment by rougier** [comment]
@ThomasA If you're more comfortable with your procedure, go ahead.

**Comment by khinsen** [comment]
Perhaps we should revise the instructions for editors, proposing two levels:
 - For git experts, describe the outcome, i.e. what the archive repository must contain, and let them get there however they want
 - For less experienced git users, provide an explicit step-by-step procedure that works in as many imaginable circumstances as possible

In the long run it would be nice to automate such management tasks, but writing the code and testing it is likely to be a major effort.

**Comment by ThomasA** [comment]
Deleting unused branches can also be a way to do it. I would liken it to a subtractive vs additve manufacturing approach where I am probably more in favour of the additive one ;-)
I still find the guidelines confusing, though. Once the author repo has been imported to ReScience-Archives, they are identical. From there you could instruct the editor to clone the newly imported archive repo and work on that instead of working on a clone of the original author archive and then adding the archive repo as a new remote to push the results to that. It only adds extra complexity to involve two repos which are really identical as a result of the import.

**Comment by pdebuyl** [comment]
@rougier I believe I just did not think of deleting the non-master branch, I'll check

**Comment by ThomasA** [comment]
By the way, where should the article metadata be stored?
> * Update article metadata

**Comment by ThomasA** [comment]
Ah OK, in the article Markdown file, it seems :o)

**Comment by khinsen** [comment]
@ThomasA Wow, logic and nature - strong words for what I see as pragmatic choices made by GitHub for a use case rather different from ours. But I agree with your analysis: in order to be able to use GitHub PRs for reviewing, we have to use repository arrangements that are not quite intuitive in the context of publishing. It actually makes more sense (to me at least) to reason about ReScience in terms of branches rather than repositories.

**Comment by ThomasA** [comment]
@khinsen Well, maybe too strong indeed :-)

What if ReScience-Archives were just one repository, new submissions were made as PRs to this repository, and each accepted replication (containing its files in an `Author(s)-YEAR` subfolder) would simply be a matter of merging the PR?

**Comment by pdebuyl** [comment]
That is what is done for the *SciPy conference proceedings, see https://github.com/euroscipy/euroscipy_proceedings We have ultimately one branch per volume of the proceedings.

**Comment by khinsen** [comment]
@ThomasA @pdebuyl I am rather sure we envisaged but rejected such a scheme at some point, even though I don't remember the details

One problem with a single repository for all of ReScience is the risk of messing it up by accident one day. With our current arrangement, archive repositories are safe except in the case of GitHub crashing or shutting down, because nobody ever modifies them.

**Comment by ThomasA** [comment]
@khinsen @pdebuyl The better-safe-than-sorry approach of separate repositories seems like a wise choice.
