### ISSUE TITLE
Accepting failures to replicate

### ISSUE THREAD

**Issue by pdebuyl** [ReScience/ReScience#57]
I didn't know whether to open the issue here or on the website repo but we should make it clear that failures to replicate, provided sufficiently documented and that an attempt was made at contacting the original authors. This follows from https://github.com/ReScience/ReScience-article-2/issues/8#issuecomment-311671068

**Comment by pdebuyl** [comment]
Proposed text for http://rescience.github.io/write/

At the end of section "Criteria for Publication":

> ReScience accepts negative results as well, meaning here
> a failure to replicate the original results. The authors of the failed replication
> are expected to document their claim of failure. An attempt to have contacted the
> authors of the original article is also asked to the authors of the replication.

**Comment by rougier** [comment]
There is also a note in the [FAQ](http://rescience.github.io/faq/):

**What if I fail to replicate a research result?**

Some research may not be replicable. Before declaring a research result non-replicable, we require extra caution to be taken. In addition to scrutiny of your submission by reviewers and editors, we will contact the authors of the original research, and issue a challenge to the ReScience community to spot and report (using the issue tracker) errors in your implementation. If no errors are found, your work will be accepted and the original research will be declared non-replicable.

**Comment by pdebuyl** [comment]
I made a PR for this. I'll edit the article once this is accepted
