### ISSUE TITLE
could someone build the Mondeel et al paper for me, please?

### ISSUE THREAD

**Issue by ctb** [ReScience/ReScience#69]
https://github.com/ReScience-Archives/Mondeel-Ogundipe-Westerhoff-2018/

I have spent about 4 hours trying to get pandoc and pandoc-crossref behaving properly, and can't manage it even on an AWS instance... I should be able to do the rest of the DOI minting.

**Comment by rougier** [comment]
One option is to work directly on the generated latex file and/or to ask authors to integrate the editor/reviewer/volume information and to recompile.

Good news is that we'll get rid of the pandoc stage soon (hopefully).

**Comment by pdebuyl** [comment]
see https://github.com/ReScience-Archives/Mondeel-Ogundipe-Westerhoff-2018/pull/2

**Comment by ctb** [comment]
thank you!!
