### ISSUE TITLE
what is the "read" portion of the web site?

### ISSUE THREAD

**Issue by ctb** [ReScience/ReScience#70]
at https://github.com/ReScience/ReScience/blob/master/editor-guidelines.md, it says to update the "read" portion of the web site, but the link doesn't work. Should I be updating the contents of the Volume 1 link, https://github.com/ReScience/ReScience?

**Comment by rougier** [comment]
Yes please if it is broken. What is the current link ?

**Comment by ctb** [comment]
https://github.com/ReScience/ReScience/blob/read - I'm not sure what it's supposed to be pointing to, though, should it be the header 'Archives' on the page  https://github.com/ReScience/ReScience?

**Comment by ctb** [comment]
ok, I found the instructions via https://github.com/ReScience/ReScience/blob/master/editor-guidelines.md, so what should we do with that page? happy to execute the decision.
