### ISSUE TITLE
How to deal with personal code from another repo

### ISSUE THREAD

**Issue by Lcressot** [ReScience/ReScience#77]
Hi,
My submission depends on some other code already public on github and I wanted to know if I could just mention this repo or if I had to copy it all inside this submission ?

More precisely,  I am preparing a submission that partly depends (for generating data) on another github repository. This other repository is public and is already ready to be downloaded and installed with pip package installer (it is an OpenAI gym environment).
Should I only give the link to this other repo or should I copy the entire repo inside this submission ?

Thank you very much !
Cheers,
Loic

**Comment by khinsen** [comment]
The main issue for us is the possibility of that code disappearing, if it is not a maintained package with official releases. But we could just archive it on Zenodo with the final article.

@rougier, what is your view on this?

**Comment by Lcressot** [comment]
Hi,
Thanks for your answer. If it was not clear, the other package is entirely mine and is on my own github account.

I am waiting for your colleague's opinion !

Cordially,
Loic Cressot

**Comment by rougier** [comment]
Could you "link" the other repo with Zenodo and make a release such that it is archived ? (see https://guides.github.com/activities/citable-code/).

Also, if the main code for replication is in the other repo, it might be worth to make a copy, else a Zenodo archive would be fine.

**Comment by Lcressot** [comment]
Hi,

Okay, a Zenodo archive seems to be the ideal solution. Thanks for the answer !

Cordially,
Loic

**Comment by khinsen** [comment]
If it's your own code, that's indeed the best solution: archive the version you use on Zenodo, and refer both to your GitHub repository and to the Zenodo archive in your ReScience submission.

**Comment by Lcressot** [comment]
Yes, thank you very much for your help, I appreciate it !

Have a good day,
Loic

**Comment by Lcressot** [comment]
Hi,

Sorry again, I made the zenodo archive and I was just wondering how I should mention it along with the github repo in my article.

Would it be acceptable to insert some additional buttons on the left (see idea1.png) or should I mention it with links (see idea2.png) ? Or were you thinking about another way ?

Thanks again,
Loic

**Comment by rougier** [comment]
One you get the Zenodo archive, you can cite it as a regular citation (look on zenodo, there should be a bibtex entry for your soft)

**Comment by Lcressot** [comment]
Oh I see, thank you very much for the answer !
