### ISSUE TITLE
Replication of work done by other members of your lab

### ISSUE THREAD

**Issue by diazrenata** [ReScience/ReScience#84]
Hi there! I'm wondering if a recent replication project of mine would be an appropriate submission. 

I've recently [replicated](https://github.com/diazrenata/replicate-becs/blob/master/report/ernest_2005_replication.md) a [paper](https://esajournals.onlinelibrary.wiley.com/doi/pdf/10.1890/03-3179) written by my advisor in 2005. My advisor is aware of the project, but hasn't been otherwise involved. I accessed the data from original sources online and re-coded the analyses based entirely on the descriptions in the paper and references therein. If this fits with your criteria for an independent replication, I'd certainly write it up as a manuscript and submit! But, I understand if this isn't quite appropriate.

**Comment by rougier** [comment]
Since the paper is more than a decade old and your supervisor was not involved in the replication, I think it is ok to propose it. @khinsen What do you think ?

**Comment by tpoisot** [comment]
Happy to handle this one if it gets submitted.

**Comment by khinsen** [comment]
@rougier I agree.

**Comment by rougier** [comment]
@diazrenata You're good to go then !
