### ISSUE TITLE
Replicating two papers at once

### ISSUE THREAD

**Issue by fgeoffroy** [ReScience/ReScience#85]
Hi all,

Is it conceivable to replicate the results of two different papers in the same ReScience publication?

In the case that interests me, the two papers share the same authors and the same algorithm. They only differ from each other in their initial conditions and in some assumptions in the underlying model.

**Comment by rougier** [comment]
If this is the same algorithm, that would make sense yes. The only "problem" is that we generally use the title of the original article prefix by [Re] such that when people search for the article, they'll also find the replication hopefully. In your case, you'll have to choose one of the two title. But apart from this, no problem to write a single paper out of two.

**Comment by fgeoffroy** [comment]
That's what I thought, thank you very much!
