### ISSUE TITLE
Shifting off github for ethical and practical reasons

### ISSUE THREAD

**Issue by broukema** [ReScience/ReScience#89]
Why should _ReScience C_ shift off github? I think that _ReScience C_ should consider this. Migration would take some effort, and a decision on an alternative server would not be easy. But IMHO it would be worth it. Here are the reasons (for a slightly more compact [toot](https://en.wikipedia.org/wiki/Fediverse) version, outside of Microsoft's control, see https://framapiaf.org/@boud/104105184468639522 .)

* Github favours propietary software:
  * https://www.linuxjournal.com/content/opinion-github-vs-gitlab
* Github was bought by #GAFAM:
  * https://framagit.org/passff/passff/issues/351
* Github violates scientific ethics by being racist [wide sense of the word; more pedantically, "by being discriminatory"]:
  * ethics: https://council.science/what-we-do/freedoms-and-responsibilities-of-scientists/
  * violation: https://help.github.com/en/github/site-policy/github-and-trade-controls

* Some Github IPs are spam blacklisted; users must randomly reconfirm emails:
  * http://www.sorbs.net/lookup.shtml?192.30.252.210 
This has been a practical problem for me since a few weeks ago. Github randomly asks me to reconfirm my email address, because some of its emails are bounced by my server - which checks community blacklists. Microsoft has never had a good record in terms of respecting the wider community and common ethical values.

Alternatives:
* https://codeberg.org - https://mastodon.technology/@codeberg
* https://framagit.org , but Framasoft.org has started a decentralisation process (a small citizens' association cannot support 40-50 different web services for a growing number of massive numbers of users), and AFAIK framagit.org is one of the services planned for gradually phasing out.
* ... ?

Disclaimer: I haven't completely shifted off github (yet).

Original post on the [Fediverse](https://en.wikipedia.org/wiki/Fediverse) : https://framapiaf.org/@boud/104105184468639522

**Comment by rougier** [comment]
I think we're aware of the many problems tied to the use of GitHub but it was a deliberate choice made at the time of creation of ReScience. With all its defaults, GitHub remains a popular choice for developers and at that time, it made sense to use it for a swift start. You're right that we now have alternatives, but because the journal is now established, it might be difficult to switch and would demand too much efforts I think.

**Comment by khinsen** [comment]
To add to @rougier arguments: We have been discussing the evolution of ReScience's technical infrastructure for a while, the main goal being a more automated processing workflow. And the whole scientific publishing business is undergoing rapid change. The arguments you quote are valid, and should be part of our list of criteria for future evolution, but that list also contains lots of other and partly contradictory criteria. Lots of trade-offs that need to be re-evaluated from time to time. The biggest challenge for ReScience right now is to grow its base of collaborators and authors, and for that the popularity of the GitHub platform is an important advantage. My personal hope is that in the not too remote future, we will have suitable technical infrastructure operated by and for the research community that journals like ReScience can use, much as we already use Zenodo.

**Comment by broukema** [comment]
Thanks for the explanations! 

As far as I know the takeover by Microsoft happened _after_ ReScience was created. So the most dramatic reason for considering a shift didn't yet exist at the time.

**Comment by broukema** [comment]
Here's a practical example of the sort of risk that _ReScience_  could potentially 
be subject to - semi-censorship in the github `Issues` structure. See this incident
that started going viral during the last few days:

https://medium.com/@probonopd/microsoft-loves-linux-a-little-too-much-cff91023e4b8

https://www.phoronix.com/scan.php?page=news_item&px=Microsoft-KDE-MAUI

The number of comments marked 'off-topic' or 'disruptive' and hidden to non-logged-in users
is quite impressive:
https://github.com/dotnet/maui/issues/35

Since this is only semi-censorship - plenty of logged-in users could redistribute the content
under the [Streisand effect](https://en.wikipedia.org/wiki/Streisand%20effect) if they wished to - it's probably not an immediate risk to _ReScience_. Nevertheless, I think that this can be taken as a warning that thoughts of a shift should not be delayed for too long, and backups of non-git structure (such as Issues!) should be made.
Microsoft is an authoritarian, centralised, totalitarian GAFAM corporation and its track
record does not suggest much confidence in expecting it to respect scientific community values.

**Comment by rougier** [comment]
Thanks for the link. Again, if we had resources to consider alternatives, we probably would but this might be difficult and until the threat got real, I guess we'll stick to GitHub. 
cc @oliviaguest and @benoit-girard (editors in chief)

**Comment by oliviaguest** [comment]
I respect the issues with any platform, but see no huge reason to move from GitHub at the time being. Nothing stops us from relocating in the future, of course.
