### ISSUE TITLE
ReScience website

### ISSUE THREAD

**Issue by rougier** [ReScience/ReScience#9]
Currently, the [rescience website](http://rescience.github.io) is a single html page that redirect to the [wiki](https://github.com/ReScience/ReScience/wiki). Maybe it would be worth to have a slightly more elaborated one with at least the list of published papers. Maybe something like http://jcgt.org ?

Thoughts ?

**Comment by benoit-girard** [comment]
I agree that the straightforward presentation of jcgt is probably better than the github wiki, yet still simple.

**Comment by rougier** [comment]
If someone is willing start the website...

**Comment by hlapp** [comment]
The wiki also makes it more difficult to contribute. E.g., there are a number of typos and language errors that I could easily fix in a PR, but with the wiki that's much more involved. (I'd have to clone, then generate a patch, email the patch, someone permitted to edit has to clone, apply the patch, and push.)

**Comment by rougier** [comment]
@khinsen

Yes, the ideal situation would be to be able to be able to make PR for the wiki.
I'll start investigating possible solutino. Or if anyone has experience with that problem...

**Comment by rougier** [comment]
I've found this source: http://nerds.inn.org/2014/05/19/applying-git-to-github-wikis/

**Comment by khinsen** [comment]
That looks doable. On the other hand, I don't see much of an advantage in using the Wiki instead of a simple Jekyll-based Web site. Except, of course, that someone has to set up the Web site, which is more involved than using the Wiki.

To put it differently: if we find a volunteer for setting up a better Web site, then I am all for it. I don't volunteer myself because I am absolutely no good at Web site design. The Wiki is nicer than anything I would produce myself.

**Comment by rougier** [comment]
I've setup the wiki repo at: https://github.com/ReScience/ReScience-wiki

**Comment by ido** [comment]
Hi, just stopped by to suggest setting up the ReScience website as a Hakyll or Jekyll static markdown-based site that uses pandoc to compile and is automatically generated by Travis-CI/CircleCI upon pushing to a branch, and then hosted on a DigitalOcean droplet.  Then the website can be updated with pull requests just like any other GitHub repository.  Then the pull requests can be checked and verified easily as well prior to merging.  For example, similar to what is proposed here: http://begriffs.com/posts/2014-08-12-create-static-site-with-hakyll-github.html

**Comment by rougier** [comment]
Oh, that might be a solution. Can you open a dedicated issue ?
And we still need a website designer :)

**Comment by ThomasA** [comment]
Won't pull requests work with a regular GitHub-generated Jekyll site?

**Comment by rougier** [comment]
Actually I'm working on that right now...
I was thinking of using Pelican to borrow the nice and clean style by @rossant website at http://cyrille.rossant.net

**Comment by rossant** [comment]
> I was thinking of using Pelican to borrow the nice and clean style by @rossant website at http://cyrille.rossant.net

... the spirit of which I borrowed from http://www.labri.fr/perso/nrougier/

**Comment by rougier** [comment]
Ah, this is why I like it ;) Just kidding, it's really clean.

Can we borrow your pelican style for the journal ? And possibly get some help setting it up ?

**Comment by rossant** [comment]
Sure! I wouldn't say no to a mention either ;)

I can try to give some help, although it's been a while since I set it up. Not sure I'll remember all the details. I had to hack certain things in pelican to make it work with notebooks, code highlighting, etc., but you probably won't need that. Also the build process is a bit crappy currently, I need to clean it up and use something like what @ido described, with automatic building with travis etc.

**Comment by rougier** [comment]
Ok. Also, you don't use the same repo for website/github pages, any reason ?

**Comment by ido** [comment]
Building pelicon with travis is only a short travis.yml file away.  :-) And travis can be given encrypted env vars with any deploy key you want to use to push the pelican-compiled static site to GH Pages or wherever...

**Comment by rossant** [comment]
@rougier no, I should probably have used one repo with two branches instead...

**Comment by rougier** [comment]
It seem there might be an even simpler solution from [pelican documentation](http://docs.getpelican.com/en/3.6.3/tips.html#extra-tips):

```
Tip #1:

To automatically update your Pelican site on each commit, you can create a post-commit hook.
For example, you can add the following to .git/hooks/post-commit:

pelican content -o output -s pelicanconf.py && ghp-import output && git push origin gh-pages
```

**Comment by ido** [comment]
@rougier post-commit hooks run on the client, and are local to your git repository on your machine.  They don't run centrally and they won't, for example, run whenever a pull request is made.  See GitHub's "Services" and web hooks for an analogous feature.  (Travis-CI and CircleCI do the setting up GitHub hooks/services part for you.)

**Comment by khinsen** [comment]
My understanding is that any Web-site generator other than Jekyll (which GitHub runs automatically upon a commit) must be installed and run locally by every person wishing to modify a page. I am not a fan of Jekyll, but there are good arguments for using it in the way we envisage.

**Comment by ido** [comment]
@khinsen with the Travis/Circle-CI approach I mentioned that is not the case - you could see the results even in a forked repository or by submitting a pull request and they would update on each commit/push.

**Comment by ido** [comment]
@khinsen ...without having the generator locally.

**Comment by rougier** [comment]
I've started a jekyll website, I'll upload it soon to rescience.github.io

**Comment by rougier** [comment]
I just uploaed it to https://github.com/ReScience/rescience.github.io but it is ot deployed yet (not sure how long it takes or if something's wrong with my setup)

**Comment by rougier** [comment]
@hlapp New website online at http://rescience.github.io
Comments/remarks/correction welcome.

**Comment by pdebuyl** [comment]
Nice work, thanks!

**Comment by npettiaux** [comment]
Very nice work. Is Jekyll easier/better than pelican ? Why ?

**Comment by khinsen** [comment]
The main advantage of Jekyll is that it is directly supported by GitHub. Any change to the Markdown code in the GitHub repository triggers a rebuild of the HTML pages.

Beyond that advantage specific to GitHub, the differences between Jekyll, Pelican, and the other few dozen static Web site generators are mostly matters of personal preferences and of the exact requirement of the Web site. I suspect any of them would be fine for our needs.

**Comment by rougier** [comment]
Yes, I just used the most easy for us without really considering all the alternatives. The default style by Jekyll is also great, this as one of the reason.

**Comment by npettiaux** [comment]
Thanks for the comments. pelican is also nicely integretad with github. I don't know jekyll to compare, but for the limited use of pelican that I have had, it works very nicely with github. A push also builds the new site, maybe not as simply though as pushing the markdown pages only.
