### ISSUE TITLE
Mention type of open access

### ISSUE THREAD

**Issue by pdebuyl** [ReScience/ReScience#93]
ReScience provides the "best" (in my opinion) type of open access: neither authors nor readers pay.

According to Wikipedia (and following the issue here https://github.com/openjournals/joss/issues/775 ) this is diamond or platinum open access. We could add this to the presentation of the journal.

**Comment by oliviaguest** [comment]
That seems like a good idea. In what way add it?

**Comment by pdebuyl** [comment]
What comes to mind: the README of the ReScience repo https://github.com/ReScience/ReScience, the homepage and FAQ of the website.

**Comment by oliviaguest** [comment]
Yes, I agree. Do you want to do a PR?

**Comment by pdebuyl** [comment]
done

**Comment by epogrebnyak** [comment]
Maybe ther shoudl have been a link to wikipedia attached to [platinum](https://en.wikipedia.org/wiki/Open_access#Diamond/platinum_OA) as well? The OA field is new and terminology is not as common.

**Comment by rougier** [comment]
@epogrebnyak Good point, can you make a PR?

**Comment by epogrebnyak** [comment]
@rougier , here is #99

**Comment by epogrebnyak** [comment]
No anchor to subheader seems available, just article link
